stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - develop
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker login -u "$DOCKERHUB_USERNAME" -p $DOCKERHUB_PASSWORD
    - docker push "$DOCKER_IMAGE"

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  needs:
    - build
  script:
    - apk add openssh
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
    - echo "$KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh ubuntu@"$HOST" "
      docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
      && docker pull "$DOCKER_IMAGE"
      && docker stop "$CONTAINER_NAME" || true
      && docker rm "$CONTAINER_NAME" || true
      && docker run -d --name "$CONTAINER_NAME" -p "$CONTAINER_PORT":3000 "$DOCKER_IMAGE""
